"""ideas_tablosunu_kaldir

Revision ID: a7d8ff966efd
Revises: 3997fe50be13
Create Date: 2026-07-02 21:58:06.293043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d8ff966efd'
down_revision: Union[str, Sequence[str], None] = '3997fe50be13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Baseline migration 'ideas' tablosunu index'siz olusturuyor, ama Alembic-oncesi
    # (legacy stamp edilmis) gercek kullanici DB'lerinde 'ix_ideas_id' fiilen var
    # olabilir. IF EXISTS ile her iki senaryoda da guvenli calisir.
    op.execute("DROP INDEX IF EXISTS ix_ideas_id")
    op.drop_table('ideas')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_id'), 'ideas', ['id'], unique=False)
    # ### end Alembic commands ###
