"""kaynak filtre kolonlarina index ekle

Revision ID: ff016ad9bf6e
Revises: a7d8ff966efd
Create Date: 2026-07-03 13:26:42.291517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff016ad9bf6e'
down_revision: Union[str, Sequence[str], None] = 'a7d8ff966efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resources_category_id'), 'resources', ['category_id'], unique=False)
    op.create_index(op.f('ix_resources_is_favorite'), 'resources', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_resources_is_pinned'), 'resources', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index(op.f('ix_resources_url'), 'resources', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_url'), table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_pinned'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_favorite'), table_name='resources')
    op.drop_index(op.f('ix_resources_category_id'), table_name='resources')
    # ### end Alembic commands ###
